---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio-istiod
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: {{`'{{name}}-istio-istiod'`}}
      labels:
        name: istio-istiod
    spec:
      project: istio
      source:
        repoURL: https://istio-release.storage.googleapis.com/charts
        targetRevision: {{ .Values.chartVersion }}
        chart: istiod
        helm:
          releaseName: istio-istiod
          valuesObject:
            revision: {{ .Values.chartVersion | replace "." "-" }}
            meshConfig:
              accessLogFile: /dev/stdout
              accessLogEncoding: JSON
              trustDomain: {{`'{{metadata.labels.stamp}}.local'`}}
              defaultConfig:
                holdApplicationUntilProxyStarts: true
                proxyMetadata:
                  ISTIO_META_DNS_CAPTURE: "true"
                  ISTIO_META_DNS_AUTO_ALLOCATE: "true"
            global:
              meshID: {{`'{{metadata.labels.stamp}}'`}}
              proxy:
                clusterDomain: {{`'{{metadata.labels.stamp}}.local'`}}
      destination:
        server: {{`'{{server}}'`}}
        namespace: istio-system
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
