---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio-base
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: {{`'{{name}}-istio-base'`}}
      labels:
        name: istio-base
    spec:
      project: istio
      source:
        repoURL: https://istio-release.storage.googleapis.com/charts
        targetRevision: {{ .Values.chartVersion }}
        chart: base
        helm:
          releaseName: istio-base
      destination:
        server: {{`'{{server}}'`}}
        namespace: istio-system
