---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio-nsgw
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: {{`'{{name}}-istio-nsgw'`}}
      labels:
        name: istio-nsgw
    spec:
      project: istio
      source:
        repoURL: https://istio-release.storage.googleapis.com/charts
        targetRevision: {{ .Values.chartVersion }}
        chart: gateway
        helm:
          releaseName: istio-nsgw
          valuesObject:
            revision: {{ .Values.chartVersion | replace "." "-" }}
            autoscaling:
              enabled: false
      destination:
        server: {{`'{{server}}'`}}
        namespace: istio-system
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
