---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio-istiod
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: {{`'{{name}}-istio-base'`}}
      labels:
        name: istio-istiod
    spec:
      project: istio
      source:
        repoURL: https://istio-release.storage.googleapis.com/charts
        targetRevision: {{ .Values.chartVersion }}
        chart: istiod
        helm:
          releaseName: istio-istiod
      destination:
        server: {{`'{{server}}'`}}
        namespace: istio-system
      syncPolicy:
        syncOptions:
        - CreateNamespace=true