---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prometheus
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: kube-00
        server: https://kubernetes.default.svc
  template:
    metadata:
      name: {{`'{{name}}-prometheus'`}}
      labels:
        name: prometheus
    spec:
      project: monitoring
      source:
        repoURL: https://prometheus-community.github.io/helm-charts
        targetRevision: {{ .Values.chartVersion }}
        chart: prometheus
        helm:
          releaseName: prometheus
          valuesObject:
            alertmanager:
              enabled: false
            kube-state-metrics:
              enabled: false
            prometheus-node-exporter:
              enabled: false
            prometheus-pushgateway:
              enabled: false
            server:
              service:
                type: LoadBalancer
                servicePort: 83
                annotations:
                  coredns.io/hostname: prometheus.demo.lab
              extraFlags:
                - web.enable-remote-write-receiver
                - web.enable-lifecycle
            serverFiles:
              prometheus.yml:
                scrape_configs:
                  - job_name: 'dummy'
                    metrics_path: /nonexistent
                    static_configs:
                      - targets: ['localhost:65535']
      destination:
        server: {{`'{{server}}'`}}
        namespace: monitoring
