---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prometheus
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: kube-00
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: {{`'{{cluster}}-prometheus'`}}
      labels:
        name: prometheus
    spec:
      project: prometheus
      source:
        repoURL: https://prometheus-community.github.io/helm-charts
        targetRevision: 25.21.0
        chart: prometheus
        helm:
          releaseName: prometheus
          values: |
            alertmanager:
              enabled: false
            kube-state-metrics:
              enabled: false
            prometheus-node-exporter:
              enabled: false
            prometheus-pushgateway:
              enabled: false
            server:
              extraArgs:
                web.enable-remote-write-receiver: null
      destination:
        server: {{`'{{url}}'`}}
        namespace: prometheus
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
