---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: httpbin
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: httpbin
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: '{{name}}-httpbin'
    spec:
      project: httpbin
      source:
        repoURL: https://github.com/h0tbird/httpbin.git
        targetRevision: HEAD
        path: .
        helm:
          values: |
            domain: red-balloon.local
      destination:
        server: '{{server}}'
        namespace: httpbin
