---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: istio
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio-base
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: '{{name}}-istio-base'
    spec:
      project: istio
      source:
        repoURL: https://github.com/h0tbird/istio.git
        targetRevision: HEAD
        path: charts/base
        helm:
          valueFiles:
          - '../../values/{{name}}.yaml'
      destination:
        server: '{{server}}'
        namespace: istio-system
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio-cni
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: '{{name}}-istio-cni'
    spec:
      project: istio
      source:
        repoURL: https://github.com/h0tbird/istio.git
        targetRevision: HEAD
        path: charts/cni
        helm:
          valueFiles:
          - '../../values/{{name}}.yaml'
      destination:
        server: '{{server}}'
        namespace: istio-system
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio-pilot
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: '{{name}}-istio-pilot'
    spec:
      project: istio
      source:
        repoURL: https://github.com/h0tbird/istio.git
        targetRevision: HEAD
        path: charts/pilot
        helm:
          valueFiles:
          - '../../values/{{name}}.yaml'
      destination:
        server: '{{server}}'
        namespace: istio-system
      ignoreDifferences:
      - group: "*"
        kind: "*"
        managedFieldsManagers:
        - pilot-discovery
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio-igws
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: '{{name}}-istio-igws'
    spec:
      project: istio
      source:
        repoURL: https://github.com/h0tbird/istio.git
        targetRevision: HEAD
        path: charts/igws
        helm:
          valueFiles:
          - '../../values/{{name}}.yaml'
      destination:
        server: '{{server}}'
        namespace: istio-system
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio-ewgw
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: '{{name}}-istio-ewgw'
    spec:
      project: istio
      source:
        repoURL: https://github.com/h0tbird/istio.git
        targetRevision: HEAD
        path: charts/ewgw
        helm:
          valueFiles:
          - '../../values/{{name}}.yaml'
      destination:
        server: '{{server}}'
        namespace: istio-system
