---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cert-manager
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: '{{name}}-cert-manager'
    spec:
      project: cert-manager
      source:
        repoURL: https://charts.jetstack.io
        targetRevision: v1.11.0
        chart: cert-manager
        helm:
          values: |
            installCRDs: true
      destination:
        server: '{{server}}'
        namespace: cert-manager
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
