---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: igw-selfsigned-issuer
  namespace: istio-system
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: demo-com
  namespace: istio-system
spec:
  issuerRef:
    kind: Issuer
    name: igw-selfsigned-issuer
  secretName: demo-com
  commonName: "*.demo.com"
  dnsNames:
  - "*.demo.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ingress-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: demo-com
    hosts:
    - 'httpbin.demo.com'
