# Debug:
# k --context kube-01 -n httpbin exec -it deployments/sleep -c istio-proxy -- sudo bash -c 'echo 0 > /proc/sys/kernel/yama/ptrace_scope'
# k --context kube-01 -n httpbin exec -it deployments/sleep -c istio-proxy -- dlv dap --listen=:40000 --log=true
# k --context kube-01 -n httpbin port-forward deployments/sleep 40000:40000

# Any ARG before the first FROM can be used in any FROM line
ARG VERSION=latest

#------------------------------------------------------------------------------
# Buildtime
#------------------------------------------------------------------------------

FROM golang:1.22 AS builder

# Build arguments
ARG VERSION="unknown"
ARG REGISTRY="unknown"
ARG GIT_SHA="unknown"

# Cache dependencies
WORKDIR /workspace
COPY go.mod go.mod
COPY go.sum go.sum
RUN go mod download

# Copy the code
COPY pilot/ pilot/
COPY pkg/ pkg/
COPY operator/ operator/
COPY security/ security/
COPY tools/ tools/
COPY common/ common/

# Build
RUN CGO_ENABLED=0 go build -o pilot-agent \
  -gcflags=all="-N -l" -tags=agent -ldflags "-extldflags -static \
  -X istio.io/istio/pkg/version.buildVersion=${VERSION} \
  -X istio.io/istio/pkg/version.buildGitRevision=${GIT_SHA} \
  -X istio.io/istio/pkg/version.buildStatus=debug \
  -X istio.io/istio/pkg/version.buildTag=${VERSION} \
  -X istio.io/istio/pkg/version.buildHub=${REGISTRY} \
  -X istio.io/istio/pkg/version.buildOS=xxx \
  -X istio.io/istio/pkg/version.buildArch=yyy" \
  ./pilot/cmd/pilot-agent

# Install delve
RUN go install github.com/go-delve/delve/cmd/dlv@latest

#------------------------------------------------------------------------------
# Runtime
#------------------------------------------------------------------------------

FROM istio/proxyv2:${VERSION}

# Copy binaries and source code
COPY --from=builder /go/bin/dlv /usr/local/bin/dlv
COPY --from=builder /workspace /workspace
COPY --from=builder /go /go
RUN mv /workspace/pilot-agent /usr/local/bin/
