# Build and deploy:
# make pilot-discovery
# k --context kind-pasta-1 -n istio-system set image deploy/istiod-1-28-2 discovery=ghcr.io/h0tbird/pilot:1.28.2-patch.1

# Debug:
# k --context kind-pasta-1 -n istio-system exec -it deploy/istiod-1-28-2 -- dlv dap --listen=:40000 --log=true
# k --context kind-pasta-1 -n istio-system port-forward deploy/istiod-1-28-2 40000:40000

# Any ARG before the first FROM can be used in any FROM line
ARG BASE_IMAGE_TAG=latest

#------------------------------------------------------------------------------
# Buildtime
#------------------------------------------------------------------------------

FROM golang:1.25 AS builder

# Build arguments
ARG VERSION="unknown"
ARG REGISTRY="unknown"
ARG GIT_SHA="unknown"

# Cache dependencies
WORKDIR /workspace
COPY go.mod go.mod
COPY go.sum go.sum
RUN go mod download

# Copy the code
COPY pilot/ pilot/
COPY pkg/ pkg/
COPY operator/ operator/
COPY security/ security/
COPY tools/ tools/
COPY common/ common/
COPY manifests/ manifests/

# Build
RUN CGO_ENABLED=0 go build -o pilot-discovery \
  -gcflags=all="-N -l" -ldflags "-extldflags -static \
  -X istio.io/istio/pkg/version.buildVersion=${VERSION} \
  -X istio.io/istio/pkg/version.buildGitRevision=${GIT_SHA} \
  -X istio.io/istio/pkg/version.buildStatus=debug \
  -X istio.io/istio/pkg/version.buildTag=${VERSION} \
  -X istio.io/istio/pkg/version.buildHub=${REGISTRY} \
  -X istio.io/istio/pkg/version.buildOS=${TARGETOS} \
  -X istio.io/istio/pkg/version.buildArch=${TARGETARCH}" \
  ./pilot/cmd/pilot-discovery

# Install delve
RUN go install github.com/go-delve/delve/cmd/dlv@latest

#------------------------------------------------------------------------------
# Runtime
#------------------------------------------------------------------------------

FROM istio/pilot:${BASE_IMAGE_TAG}

USER 0:0

# Copy binaries and source code
COPY --from=builder /go/bin/dlv /usr/local/bin/dlv
COPY --from=builder /workspace /workspace
COPY --from=builder /go /go
RUN mv /workspace/pilot-discovery /usr/local/bin/

USER 1337:1337
