# Debug:
# k --context kube-01 -n istio-system exec -it deployments/istiod-1-22-2 -- dlv dap --listen=:40000 --log=true
# k --context kube-01 -n istio-system port-forward deployments/istiod-1-22-2 40000:40000

ARG VERSION=latest

#------------------------------------------------------------------------------
# Buildtime
#------------------------------------------------------------------------------

FROM golang:1.22 AS builder

WORKDIR /workspace

# Cache dependencies
COPY go.mod go.mod
COPY go.sum go.sum
RUN go mod download

# Copy the code
COPY pilot/ pilot/
COPY pkg/ pkg/
COPY operator/ operator/
COPY security/ security/
COPY tools/ tools/
COPY common/ common/
COPY manifests/ manifests/

# Build
RUN CGO_ENABLED=0 go build -o pilot-discovery \
-gcflags=all="-N -l" -ldflags '-extldflags "-static" \
-X istio.io/istio/pkg/version.buildVersion=${VERSION} \
-X istio.io/istio/pkg/version.buildGitRevision=44d0e58e49d0dc89e27fc4f8679c68132d46b887 \
-X istio.io/istio/pkg/version.buildStatus=debug \
-X istio.io/istio/pkg/version.buildTag=${VERSION} \
-X istio.io/istio/pkg/version.buildHub=docker.io/h0tbird' \
./pilot/cmd/pilot-discovery

# Install delve
RUN go install github.com/go-delve/delve/cmd/dlv@latest

#------------------------------------------------------------------------------
# Runtime
#------------------------------------------------------------------------------

FROM istio/pilot:${VERSION}

USER 0:0

# Copy binaries and source code
COPY --from=builder /go/bin/dlv /usr/local/bin/dlv
COPY --from=builder /workspace /workspace
COPY --from=builder /go /go
RUN mv /workspace/pilot-discovery /usr/local/bin/

USER 1337:1337
