# git checkout 1.22.2
# git rev-parse HEAD

# Single arch:
# docker build -t h0tbird/pilot:1.22.2 -f Dockerfile.pilot-discovery .

# Multi arch:
# docker buildx create --name mybuilder --use
# docker buildx build --platform linux/amd64,linux/arm64 -t h0tbird/pilot:1.22.2 -f Dockerfile.pilot-discovery --push .

# Debug:
# k --context kube-01 -n istio-system exec -it deployments/istiod-1-22-2 -- dlv dap --listen=:40000 --log=true
# k --context kube-01 -n istio-system port-forward deployments/istiod-1-22-2 40000:40000

#------------------------------------------------------------------------------
#
#------------------------------------------------------------------------------

FROM golang:1.22 AS builder

WORKDIR /workspace

# Cache dependencies
COPY go.mod go.mod
COPY go.sum go.sum
RUN go mod download

# Copy the code
COPY pilot/ pilot/
COPY pkg/ pkg/
COPY operator/ operator/
COPY security/ security/
COPY tools/ tools/
COPY common/ common/
COPY manifests/ manifests/

# Build
RUN CGO_ENABLED=0 go build -o pilot-discovery -gcflags=all="-N -l" -ldflags '\
-extldflags "-static -s -w" \
-X istio.io/istio/pkg/version.buildVersion=1.22.2 \
-X istio.io/istio/pkg/version.buildGitRevision=204da5ba47f295a8dc56936333e692f6a8707649 \
-X istio.io/istio/pkg/version.buildStatus=debug \
-X istio.io/istio/pkg/version.buildTag=1.22.2 \
-X istio.io/istio/pkg/version.buildHub=docker.io/h0tbird' \
./pilot/cmd/pilot-discovery

# Install delve
RUN go install github.com/go-delve/delve/cmd/dlv@latest

#------------------------------------------------------------------------------
#
#------------------------------------------------------------------------------

FROM istio/pilot:1.22.2

USER 0:0

# Install tools
# RUN apt-get update && apt-get install -y --no-install-recommends \
#     file && rm -rf /var/lib/apt/lists/*

# Copy binaries and source code
COPY --from=builder /go/bin/dlv /usr/local/bin/dlv
COPY --from=builder /workspace /workspace
COPY --from=builder /go /go
RUN mv /workspace/pilot-discovery /usr/local/bin/

USER 1337:1337
