#!/bin/bash

HOST=/mnt/host
VM_FILES=${HOST}/vm-files

dpkg -i ${HOST}/istio-sidecar.deb
mkdir -p /var/run/secrets/tokens
cp ${VM_FILES}/istio-token /var/run/secrets/tokens/istio-token
cp ${VM_FILES}/cluster.env /var/lib/istio/envoy/cluster.env
cp ${VM_FILES}/mesh.yaml /etc/istio/config/mesh
cat ${VM_FILES}/hosts >> /etc/hosts

chown -R istio-proxy \
  /var/lib/istio \
  /etc/certs \
  /etc/istio/proxy \
  /etc/istio/config \
  /var/run/secrets \
  /etc/certs/root-cert.pem
