---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: {{`'{{name}}-cert-manager'`}}
      labels:
        name: cert-manager
    spec:
      project: cert-manager
      source:
        repoURL: https://charts.jetstack.io
        targetRevision: {{ .Values.chartVersion }}
        chart: cert-manager
        helm:
          releaseName: cert-manager
          valuesObject:
            installCRDs: true
            clusterResourceNamespace: istio-system
      destination:
        server: {{`'{{server}}'`}}
        namespace: cert-manager
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
