---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applab-blau
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: '{{name}}-applab-blau'
      labels:
        name: applab-blau
    spec:
      project: applab
      source:
        repoURL: https://github.com/h0tbird/applab.git
        targetRevision: HEAD
        path: .
        helm:
          releaseName: blau
          values: |
            domain: {{metadata.labels.stamp}}.local
      destination:
        server: '{{server}}'
        namespace: applab-blau
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
