---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio-issuers
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: '{{name}}-istio-issuers'
    spec:
      project: cert-manager
      source:
        repoURL: https://github.com/h0tbird/istio.git
        targetRevision: HEAD
        path: charts/issuers
        helm:
          values: |
            # TODO
            # mesh: red-balloon
            # network: {{name}}
            # cluster: {{name}}
            # domain: cluster.local
            # revision: 1-17-1
            # trustDomain: red-balloon.local
      destination:
        server: '{{server}}'
        namespace: istio-system
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
