---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio-cni
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: '{{name}}-istio-cni'
    spec:
      project: istio
      source:
        repoURL: https://github.com/h0tbird/istio.git
        targetRevision: HEAD
        path: charts/cni
        helm:
          values: |
            mesh: red-balloon
            network: {{name}}
            cluster: {{name}}
            domain: red-balloon.local
            revision: 1-17-1
            trustDomain: red-balloon.local
      destination:
        server: '{{server}}'
        namespace: istio-system
