---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio-issuers
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: '{{name}}-istio-issuers'
    spec:
      project: cert-manager
      source:
        # TODO
      destination:
        server: '{{server}}'
        namespace: istio-system
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
