---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio-ewgw
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: {{`'{{name}}-istio-ewgw'`}}
      labels:
        name: istio-ewgw
    spec:
      project: istio
      source:
        repoURL: https://github.com/h0tbird/meshlab.git
        targetRevision: HEAD
        path: charts/ewgw
        helm:
          releaseName: istio-ewgw
          valuesObject:
            network: {{`'{{name}}'`}}
      destination:
        server: {{`'{{server}}'`}}
        namespace: istio-system
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
