---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio-base
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: {{`'{{name}}-istio-base'`}}
      labels:
        name: istio-base
    spec:
      project: istio
      source:
        repoURL: https://istio-release.storage.googleapis.com/charts
        targetRevision: {{ .Values.chartVersion }}
        chart: base
        helm:
          releaseName: istio-base
          valuesObject:
            defaultRevision: {{ .Values.chartVersion | replace "." "-" }}
      destination:
        server: {{`'{{server}}'`}}
        namespace: istio-system
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        managedNamespaceMetadata:
          labels:
            topology.istio.io/network: {{`'{{metadata.labels.cell}}'`}}
      ignoreDifferences:
      - group: admissionregistration.k8s.io
        kind: ValidatingWebhookConfiguration
        jsonPointers:
        - /webhooks/0/failurePolicy
