name: Deploy Book
on:
  workflow_dispatch: {}
  pull_request:
    paths:
      - 'docs/book/src/**'
  push:
    branches:
      - master
    paths:
      - 'docs/book/src/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

    # Checkout the repository
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Setup mdBook
    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: '0.4.43'

    # Build the book
    - name: Build the book
      working-directory: docs/book
      run: mdbook build

    # Deploy the book
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      if: github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/book/book
