name: Deploy Book
on:
  workflow_dispatch: {}
  pull_request:
    paths:
      - 'docs/book/src/**'
  push:
    paths:
      - 'docs/book/src/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/h0tbird/meshlab-devcontainer
    permissions:
      contents: write
    steps:

    # Checkout the repository
    - name: Checkout
      uses: actions/checkout@v3

    # Build the book
    - name: Build the book
      working-directory: docs/book
      run: mdbook build

    # Setup git
    - name: Setup git
      run: |
        git config --global --add safe.directory /__w/meshlab/meshlab
        git config user.name "Deploy from CI"
        git config user.email ""

    # The gh-pages branch is used to host the book
    - name: Deploy
      working-directory: docs/book
      run: |
        git worktree add gh-pages
        cd gh-pages
        git update-ref -d refs/heads/gh-pages
        rm -rf *
        cp -r ../book/* .
        git add .
        git commit -m "Deploy $GITHUB_SHA to gh-pages"
        git push --force --set-upstream origin gh-pages