name: Deploy Book
on:
  workflow_dispatch: {}
  pull_request:
    paths:
      - 'docs/book/src/**'
  push:
    paths:
      - 'docs/book/src/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/h0tbird/meshlab-devcontainer
    permissions:
      contents: write
    steps:

    # Checkout the repository
    - name: Checkout
      uses: actions/checkout@v3

    # Build the book
    - name: Build the book
      working-directory: docs/book
      run: mdbook build

    # Deploy the book
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      # if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/book/book
