name: Pre-build dev container image
on:
  workflow_dispatch: {}
  pull_request:
    paths:
      - '.devcontainer/**'
  push:
    paths:
      - '.devcontainer/**'
jobs:
  pre_build:
    runs-on: ubuntu-latest
    steps:
      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/h0tbird/meshlab-devcontainer
          cacheFrom: ghcr.io/h0tbird/meshlab-devcontainer
          push: always
