name: Pre-build devcontainer image
on:
  workflow_dispatch: {}
  pull_request:
    paths:
      - '.devcontainer/**'
  push:
    paths:
      - '.devcontainer/**'
jobs:
  pre_build:
    runs-on: ubuntu-latest
    steps:

    # Checkout the repository
    - name: Checkout
      uses: actions/checkout@v3

    # Login to the GitHub Container Registry
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Build the devcontainer
    - name: Pre-build devcontainer image
      uses: devcontainers/ci@v0.3
      with:
        imageName: ghcr.io/h0tbird/meshlab-devcontainer
        cacheFrom: ghcr.io/h0tbird/meshlab-devcontainer
        push: always
