name: Pre-build devcontainer image
on:
  workflow_dispatch: {}
  pull_request:
    paths:
      - '.devcontainer/**'
  push:
    paths:
      - '.devcontainer/**'
jobs:
  pre_build:
    runs-on: ubuntu-latest
    steps:

    # Checkout the repository
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Build the devcontainer
    - name: Pre-build devcontainer image
      uses: devcontainers/ci@v0.3
      with:
        imageName: ghcr.io/h0tbird/meshlab-devcontainer
        cacheFrom: ghcr.io/h0tbird/meshlab-devcontainer
        push: always
