---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: vault
  source:
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.23.0
    chart: vault
    helm:
      values: |
        server:
          dev:
            enabled: true
            devRootToken: root
          service:
            type: LoadBalancer
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
