---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: otel-collector
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: {{`'{{name}}-otel-collector'`}}
      labels:
        name: otel-collector
    spec:
      project: monitoring
      source:
        repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
        targetRevision: 0.92.0
        chart: opentelemetry-collector
        helm:
          releaseName: opentelemetry-collector
          values: |
            image:
              repository: otel/opentelemetry-collector-k8s
            mode: daemonset
            config:
              receivers:
                jaeger: null
                otlp: null
                prometheus: null
                zipkin: null
              service:
                pipelines:
                  traces: null
                  metrics: null
                  logs: null
            ports:
              jaeger-compact:
                enabled: false
              jaeger-thrift:
                enabled: false
              jaeger-grpc:
                enabled: false
              otlp:
                enabled: false
              otlp-http:
                enabled: false
              zipkin:
                enabled: false
      destination:
        server: {{`'{{server}}'`}}
        namespace: monitoring
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
