---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: otelco-node
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: {{`'{{name}}-otelco-node'`}}
      labels:
        name: otelco-node
    spec:
      project: monitoring
      source:
        repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
        targetRevision: {{ .Values.chartVersion }}
        chart: opentelemetry-collector
        helm:
          releaseName: otelco-node
          values: |
            image:
              repository: otel/opentelemetry-collector-contrib
            mode: daemonset
            presets:
              kubernetesAttributes:
                enabled: true
              kubeletMetrics: # https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/kubeletstatsreceiver/documentation.md
                enabled: true
            config:
              receivers:
                jaeger: null
                zipkin: null
                prometheus:
                  config:
                    scrape_configs:
                    - job_name: envoy
                      metrics_path: /stats/prometheus
                      kubernetes_sd_configs:
                      - role: pod
                      relabel_configs: # Before scrape; select targets.
                      - source_labels: [__meta_kubernetes_pod_node_name]
                        action: keep
                        regex: '${env:K8S_NODE_NAME}'
                      - source_labels: [__meta_kubernetes_pod_container_port_name]
                        action: keep
                        regex: '.*-envoy-prom'
                      metric_relabel_configs: # Before ingest; manipulate metrics.
                      - source_labels: [__name__]
                        regex: 'envoy_listener_manager_worker_(.*)_dispatcher_(?:loop_duration|poll_delay)_us_(?:bucket|count|sum)'
                        target_label: worker
                        replacement: '$${1}'
                      - source_labels: [__name__]
                        regex: '(envoy_listener_manager)_worker_(?:.*)_(dispatcher_(?:loop_duration|poll_delay)_us)_(bucket|count|sum)'
                        target_label: __name__
                        replacement: '$${1}_$${2}_$${3}'
              processors:
                resource:
                  attributes:
                    - key: k8s.cluster.name
                      value: {{`'{{name}}'`}}
                      action: upsert
              exporters:
                prometheusremotewrite:
                  endpoint: http://prometheus.mesh.lab:83/api/v1/write
                  resource_to_telemetry_conversion:
                    enabled: true
                  tls:
                    insecure: true
                debug:
                  verbosity: detailed
              service:
                pipelines:
                  traces: null
                  logs: null
                  metrics:
                    receivers: [prometheus, kubeletstats]
                    processors: [resource, batch]
                    exporters: [prometheusremotewrite, debug]
            ports:
              jaeger-compact:
                enabled: false
              jaeger-thrift:
                enabled: false
              jaeger-grpc:
                enabled: false
              zipkin:
                enabled: false
      destination:
        server: {{`'{{server}}'`}}
        namespace: monitoring
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
