---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: otel-collector
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: {{`'{{name}}-otel-collector'`}}
      labels:
        name: otel-collector
    spec:
      project: monitoring
      source:
        repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
        targetRevision: 0.92.0
        chart: opentelemetry-collector
        helm:
          releaseName: opentelemetry-collector
          valuesObject:
            image:
              repository: otel/opentelemetry-collector-k8s
            mode: daemonset
      destination:
        server: {{`'{{server}}'`}}
        namespace: monitoring
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
